{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled (not .Values.admissionWebhooks.certManager.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "prometheus-operator.patch-job.fullname" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels: {{ include "prometheus-operator.admission.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name:  {{ template "prometheus-operator.patch-job.fullname" . }}
{{- with .Values.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels: {{ include "prometheus-operator.admission.labels" . | nindent 8 }}
    spec:
      {{- if .Values.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      containers:
        - name: patch
          {{- if .Values.admissionWebhooks.patch.image.sha }}
          image: {{ .Values.admissionWebhooks.patch.image.repository }}:{{ .Values.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ .Values.admissionWebhooks.patch.image.repository }}:{{ .Values.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ template "prometheus-operator.admission.fullname" . }}
            - --namespace={{ template "prometheus-operator.namespace" . }}
            - --secret-name={{ template "prometheus-operator.admission.fullname" . }}
            - --patch-failure-policy={{ .Values.admissionWebhooks.failurePolicy }}
          resources:
{{ toYaml .Values.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "prometheus-operator.admission.fullname" . }}
      {{- with .Values.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
{{- end }}
