{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled .Values.global.rbac.create (not .Values.admissionWebhooks.certManager.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "prometheus-operator.admission.fullname" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels: {{ include "prometheus-operator.admission.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus-operator.admission.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.admission.fullname" . }}
    namespace: {{ template "prometheus-operator.namespace" . }}
{{- end }}
