{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheus-operator.fullname" . }}
  labels: {{ include "prometheus-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-operator.serviceAccountName" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
{{- end }}
