{{- if .Values.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels: {{ include "prometheus-operator.labels" . | nindent 4 }}
spec:
  endpoints:
  {{- if .Values.tls.enabled }}
  - port: https
    scheme: https
    tlsConfig:
      serverName: {{ template "prometheus-operator.fullname" . }}
      ca:
        secret:
          name: {{ template "prometheus-operator.admission.fullname" . }}
          key: {{ if .Values.admissionWebhooks.certManager.enabled }}ca.crt{{ else }}ca{{ end }}
          optional: false
  {{- else }}
  - port: http
  {{- end }}
    honorLabels: true
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  selector:
    matchLabels: {{ include "prometheus-operator.matchLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "prometheus-operator.namespace" .) | quote }}
{{- end }}
