{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.serviceAccountName" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels: {{ include "prometheus-operator.labels" . | nindent 4 }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
