apiVersion: v2
description: The chart deployes the Promethes Operator
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
engine: gotpl
type: application
maintainers:
  - name: langecode
    email: tal@netic.dk
name: prometheus-operator
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/prometheus-operator
version: 0.1.0
appVersion: 0.46.0
kubeVersion: ">=1.16.0-0"
home: https://github.com/prometheus-operator/prometheus-operator
keywords:
- operator
- prometheus
annotations:
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
